services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env-non-dev
    networks:
      - custom

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - custom

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    depends_on:
      - app
    volumes:
      - .:/etc/prometheus
    networks:
      - custom

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - custom
    volumes:
      - grafana_data:/etc/grafana
    user: "0"

networks:
  custom:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
